GradFolio Application/GradFolio/GradFolio.Web/Controllers/GradFolioController.cs
using System.Web.Mvc;
using GradFolio.Core.Services;

namespace GradFolio.Web.Controllers
{
    public class GradFolioController : Controller
    {

        private readonly ILoggingService _loggingService;
        private readonly IPortfolioService _portfolioService;

        public GradFolioController(
            ILoggingService loggingService, 
            IPortfolioService portfolioService)
        {
            _loggingService = loggingService;
            _portfolioService = portfolioService;
        }


        // GET: GradFolio
        public ActionResult Index(long id)
        {
            var model = _portfolioService.GetPortfolioByRefNum(id);
            return View(model);
        }
    }
}

GradFolio Application/GradFolio/GradFolio.Web/Controllers/PortfolioController.cs
using System.Web.Mvc;
using GradFolio.Core.DTO;
using GradFolio.Core.Services;
using GradFolio.Core.ViewModels;
using Microsoft.AspNet.Identity;

namespace GradFolio.Web.Controllers
{
    [Authorize]
    public class PortfolioController : Controller
    {
        //public string UserId = "d5390018-e4ba-4ae4-add2-aaaa634f1a92";

        private readonly ILoggingService _loggingService;
        private readonly IPortalService _portalService;
        private readonly IPortfolioService _portfolioService;

        public PortfolioController(
            IPortalService portalService,
            IPortfolioService portfolioService,
            ILoggingService loggingService)
        {
            _portalService = portalService;
            _portfolioService = portfolioService;
            _loggingService = loggingService;
        }

        [HttpGet]
        public ActionResult PortfolioOverview()
        {
            var overview = GetOverview(User.Identity.GetUserId());
            return PartialView("_PortfolioOverview", overview);
        }


        [HttpGet]
        public ActionResult AddPortfolio()
        {
            return PartialView("_AddPortfolio");
        }

        [HttpPost]
        [ActionName("AddPortfolio")]
        public ActionResult AddPortfolioPost()
        {
            var portfolio = new PortfolioDto()
            {
                Type = "Template1",
                UserId = User.Identity.GetUserId()
            };
            var isAdded = _portfolioService.InsertPortfolio(portfolio, User.Identity.GetUserId());

            return Json(ModelState.IsValid ? new {success = true} : new {success = false});
        }


        [HttpGet]
        public ActionResult RemovePortfolio(string itemId)
        {
            var portfolio = GetOverview(User.Identity.GetUserId()).Portfolio;
            return PartialView("_RemovePortfolio", portfolio);
        }

        [HttpPost]
        [ActionName("RemovePortfolio")]
        public ActionResult RemovePortfolioPost(string id)
        {
            {
                var isDeleted = _portfolioService.DeletePortfolio(User.Identity.GetUserId(), id);
                if (isDeleted)
                {
                    return Json(new {success = true});
                }
            }
            var portfolio = GetOverview(User.Identity.GetUserId()).Portfolio;
            ModelState.AddModelError(string.Empty, "The item cannot be removed");
            return PartialView("_RemovePortfolio", portfolio);
        }


        private PortfolioViewModel GetOverview(string userId)
        {
            var overview = new PortfolioViewModel
            {
                Stats = CheckStatus(userId),
                Portfolio = GetPortfolio(userId)
            };

            if (overview.Stats.ProfileCount == 1 && overview.Stats.ExperienceCount >= 2 &&
                overview.Stats.CourseCount >= 2 && overview.Stats.SkillCount >= 2
                && overview.Stats.AwardCount >= 2 && overview.Stats.InterestCount >= 2
                && overview.Stats.ProjectCount >= 2 && overview.Stats.CvCount >=0)
            {
                overview.IsReady = true;
            }
            return overview;
        }

        private PortfolioModel GetPortfolio(string userId)
        {
            var query = _portfolioService.GetPortfolioByUserId(userId);
            if (query != null)
            {
                return new PortfolioModel
                {
                    Id = query.Id,
                    Type = query.Type,
                    RefNum = query.RefNum,
                    CreateDate = query.CreateDate
                };
            }
            return null;
        }

        private PortalOverviewStats CheckStatus(string userId)
        {
            var query = _portalService.GetPortalOverview(userId);
            if (query == null) return null;

            var stats = new PortalOverviewStats
            {
                ProfileCount = query.ProfileCount,
                ExperienceCount = query.ExperienceCount,
                CourseCount = query.CourseCount,
                SkillCount = query.SkillCount,
                AwardCount = query.AwardCount,
                InterestCount = query.InterestCount,
                ProjectCount = query.ProjectCount,
                PortfolioCount = query.PortfolioCount
            };
            return stats;
        }
    }
}

GradFolio Application/GradFolio/GradFolio.Web/Views/Portfolio/_AddPortfolio.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="modal-header" style="background-color: #000000; color: #f5fffa">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" style="color: #ffffff">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add Portfolio</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="alert alert-warning" role="alert">You are about to generate a portfolio click okay to proceed!!</div>
            </div>
        </div>
    </div>
    <div class="modal-footer" style="background-color: #000000; color: #f5fffa">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="btn-content-add-submit" type="button" class="btn btn-primary">Okay Go!</button>
    </div>
}

GradFolio Application/GradFolio/GradFolio.Web/Views/Portfolio/_PortfolioOverview.cshtml
@model GradFolio.Core.ViewModels.PortfolioViewModel

<div class="row">
<div class="col-lg-6 col-md-6 col-xs-12">
    <div class="thumbnail">
        <ul class="list-group" style="margin-bottom: 0;">
            <li class="list-group-item">
                <h4>
                    Overall Status
                </h4>
            </li>
            <li class="list-group-item">
                <span> Profile:  </span>

                @if (Model.Stats.ProfileCount == 1)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
            </li>
            <li class="list-group-item">
                <span> Experience:  </span>

                @if (Model.Stats.ExperienceCount > 1)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }

            </li>
            <li class="list-group-item">
                <span> Courses:  </span>

                @if (Model.Stats.CourseCount > 1)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }

            </li>
            <li class="list-group-item">
                <span> Skills:  </span>

                @if (Model.Stats.SkillCount > 1)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
            </li>
            <li class="list-group-item">
                <span> Awards:  </span>


                @if (Model.Stats.AwardCount > 1)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
            </li>
            <li class="list-group-item">
                <span> Interests:  </span>

                @if (Model.Stats.InterestCount > 1)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }

            </li>
            <li class="list-group-item">
                <span> Projects:  </span>

                @if (Model.Stats.ProjectCount > 1)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
            </li>

            <li class="list-group-item">
                <span> CV:  </span>

                @if (Model.Stats.CvCount > 0)
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
                else
                {
                    <span class="label label-success pull-right">
                        <span class=" glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                    </span>
                }
            </li>
            <li class="list-group-item">
                <div class="radio">
                    <label><input type="radio" name="optradio" checked>Portfolio Template 1</label>
                    @*@Html.ActionLink("Sample Preview", "ViewCv", "CV", new {id = 1}, new {@class = "btn btn-primary btn-sm pull-right", target = "_blank"})*@
                </div>
            </li>
            <li class="list-group-item">
                @if (Model.IsReady && Model.Stats.PortfolioCount == 0)
                {
                    <button class="btn btn-success btn-sm" onclick="generatePortfolioBtnClick()" style="width: 100%;" type="button">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        Generate Curriculum Vitae
                    </button>
                }
                else
                {
                    <button class="btn btn-success btn-sm" style="width: 100%;" type="button" disabled>
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        Generate Curriculum Vitae
                    </button>
                }
            </li>
        </ul>
    </div>
</div>

<div class="col-lg-6 col-md-6 col-xs-12" style="max-height: 660px; overflow-y: auto; margin-bottom: 20px;">
    @if (Model.Portfolio != null && Model.IsReady)
    {
        <div class="col-lg-12 col-md-12 col-xs-12">
            <div class="thumbnail">
                <ul class="list-group" style="margin-bottom: 0;">
                    <li class="list-group-item">
                        <span class=" glyphicon glyphicon-education" aria-hidden="true"></span><span> Name: @Model.Portfolio.Type</span>
                    </li>
                    <li class="list-group-item">
                        <span class=" glyphicon glyphicon-education" aria-hidden="true"></span><span> Name: @Model.Portfolio.RefNum</span>
                    </li>
                    <li class="list-group-item">
                        <span class=" glyphicon glyphicon-education" aria-hidden="true"></span><span>
                            @Html.ActionLink("PortFolioLink", "Index", "GradFolio",
                                new {Id = @Model.Portfolio.RefNum}, new {@class = "", target = "_blank"})
                        </span>
                    </li>
                    <li class="list-group-item">
                        <span class=" glyphicon glyphicon-calendar" aria-hidden="true"></span>
                        <span> Create Date: @Model.Portfolio.CreateDate.ToShortDateString() </span>
                    </li>
                </ul>
            </div>
            <div class="pull-right" style="margin-bottom: 10px;">
                @*@Html.ActionLink("Preview", "ViewCv", "CV", new { id = @item.Id }, new { @class = "btn btn-primary btn-sm", target = "_blank" })*@
                <button type="button" class="btn btn-danger btn-sm" onclick="itemBtnClick('remove', '?itemId=@Model.Portfolio.Id');">Remove</button>
            </div>
        </div>
    }
    else
    {
        <div class="col-lg-12 col-md-12 col-xs-12">
            <div class="thumbnail">
                <span class=" glyphicon glyphicon-warning-sign" aria-hidden="true"></span><span> No Portfolio found!!  </span>
            </div>
        </div>
    }
</div>
</div>

GradFolio Application/GradFolio/GradFolio.Web/Views/Portfolio/_RemovePortfolio.cshtml
@model GradFolio.Core.ViewModels.PortfolioModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="modal-header" style="background-color: #000000; color: #f5fffa">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" style="color: #ffffff">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Are you sure you want to delete this?</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)


            <div class="form-group">
                @Html.LabelFor(model => model.Type, new { @class = "control-label col-lg-4 col-md-4 col-xs-12" })
                <div class="col-lg-8 col-md-8 col-xs-12">
                    @Html.DisplayFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.RefNum, new { @class = "control-label col-lg-4 col-md-4 col-xs-12" })
                <div class="col-lg-8 col-md-8 col-xs-12">
                    @Html.DisplayFor(model => model.RefNum, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Type, new { @class = "control-label col-lg-4 col-md-4 col-xs-12" })
                <div class="col-lg-8 col-md-8 col-xs-12">
                    @Html.DisplayFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CreateDate, new { @class = "control-label col-lg-4 col-md-4 col-xs-12" })
                <div class="col-lg-8 col-md-8 col-xs-12">
                    @Html.DisplayFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer" style="background-color: #000000; color: #f5fffa">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="btn-content-remove-submit" type="button" class="btn btn-danger">Remove</button>
    </div>
}

GradFolio Application/GradFolio/GradFolio.Web/Views/Portfolio/_SelectExperience.cshtml
@using MvcCheckBoxList.Model
@model GradFolio.Core.ViewModels.PortfolioSettingViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="modal-header" style="background-color: #000000; color: #f5fffa">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true" style="color: #ffffff">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Edit Award</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new {@class = "text-danger"})
            @Html.HiddenFor(model => model.SettingType)

            <div class="editor-label">
                <label>Categories</label>
            </div>

            @Html.CheckBoxListFor(model => model.PostedSettings.SettingIds,
                model => model.AvailableSettings,
                fruit => fruit.Id,
                fruit => fruit.Title,
                model => model.SelectedSettings,
                Position.Vertical)


        </div>
    </div>
    <div class="modal-footer" style="background-color: #000000; color: #f5fffa">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

        <button id="btn-content-edit-submit" type="button" class="btn btn-primary">Save changes</button>
    </div>
}