GradFolio Application/GradFolio/GradFolio.Web/Controllers/PortalController.cs
using System;
using System.Web.Mvc;
using GradFolio.Core.Services;
using GradFolio.Core.ViewModels;
using Microsoft.AspNet.Identity;

namespace GradFolio.Web.Controllers
{
    [Authorize]
    public class PortalController : Controller
    {
        //public string UserId = "d5390018-e4ba-4ae4-add2-aaaa634f1a92";
        private readonly ILoggingService _loggingService;
        private readonly IPortalService _portalService;

        public PortalController(
            IPortalService portalService,
            ILoggingService loggingService)
        {
            _portalService = portalService;
            _loggingService = loggingService;
        }


        [HttpGet]
        public ActionResult Overview()
        {
            return View();
        }

        [HttpGet]
        public ActionResult PortalOverview()
        {
            var overview = GetOverview(User.Identity.GetUserId());
            return PartialView("_PortalOverview", overview);
        }

        [HttpGet]
        public ActionResult ProfileInfo()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Experience()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Courses()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Skills()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Projects()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Awards()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Interests()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CurriculumVitae()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Portfolio()
        {
            return View();
        }


        public PortalOverviewViewModel GetOverview(string userId)
        {
            var query = _portalService.GetPortalOverview(userId);
            if (query == null) return null;


            var overview = new PortalOverviewViewModel
            {
                PortalOverviewStats = new PortalOverviewStats
                {
                    ExperienceCount = query.ExperienceCount,
                    CourseCount = query.CourseCount,
                    SkillCount = query.SkillCount,
                    AwardCount = query.AwardCount,
                    InterestCount = query.InterestCount,
                    ProjectCount = query.ProjectCount
                }
            };


            if (query.Profile != null)
            {
                overview.ProfileOverview = new ProfileOverview
                {
                    Name = query.Profile.FirstName + " " + query.Profile.LastName,
                    Title = query.Profile.Title,
                    ImageUrl = query.Profile.ImageUrl,
                    JoinDate = query.Profile.JoinDate
                };
            }

            if (query.LatestExperience != null)
            {
                overview.ExperienceOverview = new ExperienceOverview
                {
                    Title = query.LatestExperience.Title,
                    Company = query.LatestExperience.Company,
                    CreateDate = query.LatestExperience.CreateDate
                };
            }

            if (query.LatestCourse != null)
            {
                overview.CourseOverview = new CourseOverview
                {
                    Id = query.LatestCourse.Id,
                    Title = query.LatestCourse.Title,
                    College = query.LatestCourse.College,
                    CreateDate = DateTime.Now
                };
            }

            if (query.LatestSkill != null)
            {
                overview.SkillOverview = new SkillOverview
                {
                    Id = query.LatestSkill.Id,
                    Title = query.LatestSkill.Title,
                    Level = query.LatestSkill.Level,
                    CreateDate = query.LatestSkill.CreateDate
                };
            }

            if (query.LatestAward != null)
            {
                overview.AwardOverview = new AwardOverview
                {
                    Id = query.LatestAward.Id,
                    Title = query.LatestAward.Title,
                    Level = query.LatestAward.Level,
                    CreateDate = query.LatestAward.CreateDate
                };
            }

            if (query.LatestInterest != null)
            {
                overview.InterestOverview = new InterestOverview
                {
                    Id = query.LatestInterest.Id,
                    Title = query.LatestInterest.Title,
                    CreateDate = query.LatestInterest.CreateDate
                };
            }

            if (query.LatestProject != null)
            {
                overview.ProjectOverview = new ProjectOverview
                {
                    Id = query.LatestProject.Id,
                    Title = query.LatestProject.Title,
                    CreateDate = query.LatestProject.CreateDate
                };
            }


            if (query.LatestCv != null)
            {
                overview.CvOverview = new CvOverview
                {
                    Id = query.LatestCv.Id,
                    FileName = query.LatestCv.Name,
                    Type = query.LatestCv.Type,
                    CreateDate = query.LatestCv.CreateDate
                };
            }

            if (query.PortfolioCount > 0)
            {
                overview.PortfolioOverview = new PortfolioOverview
                {
                    Id = query.LatestPortfolio.Id,
                    Type = query.LatestPortfolio.Type,
                    PortfolioUrl = query.LatestPortfolio.RefNum.ToString(),
                    CreateDate = query.LatestPortfolio.CreateDate
                };
            }

            //need work


            return overview;
        }
    }
}

GradFolio Application/GradFolio/GradFolio.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>



<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("GradFolio", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            @if (User.Identity.IsAuthenticated)
            {
                <ul class="nav navbar-nav" id="menu-wrapper">
                    <li>@Html.ActionLink("Overview", "Overview", "Portal")</li>
                </ul>
            }
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>

GradFolio Application/GradFolio/GradFolio.Web/Views/Shared/_LayoutPortFolio.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/gradfoliotemp.css" rel="stylesheet" />
</head>
<body>
    
    @RenderBody()

@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)

</body>
</html>

GradFolio Application/GradFolio/GradFolio.Web/Views/Shared/_LayoutPortal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Scripts.Render("~/bundles/jquery")

    @Styles.Render("~/Content/portal")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/portal/notify-custom.min.js"></script>
</head>
<body>

<div class="container black ">
    <div class="navbar navbar-inverse navbar-static-top margin-bottom-remove">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("GradFolio Portal", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav" id="menu-wrapper">
                <li>@Html.ActionLink("Overview", "Overview", "Portal")</li>
                <li>@Html.ActionLink("ProfileInfo", "ProfileInfo", "Portal")</li>
                <li>@Html.ActionLink("Experience", "Experience", "Portal")</li>
                <li>@Html.ActionLink("Courses", "Courses", "Portal")</li>
                <li>@Html.ActionLink("Skills", "Skills", "Portal")</li>
                <li>@Html.ActionLink("Awards", "Awards", "Portal")</li>
                <li>@Html.ActionLink("Interests", "Interests", "Portal")</li>
                <li>@Html.ActionLink("Projects", "Projects", "Portal")</li>
                <li>@Html.ActionLink("CV", "CurriculumVitae", "Portal")</li>
                <li>@Html.ActionLink("Portfolio", "Portfolio", "Portal")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>

    <div class="row body-content">
        <div class="col-md-2 black" id="sidebar-wrapper">
            <div class="list-group">
                <div style="height: 22px;"></div>

                <a href="@Url.Action("Overview", "Portal")" class="list-group-item border-flatten">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Overview </span>
                </a>

                <a href="@Url.Action("ProfileInfo", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Profile </span>
                </a>

                <a href="@Url.Action("Experience", "Portal")" class=" list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Experience </span>
                </a>

                <a href="@Url.Action("Courses", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Education </span>
                </a>
                <a href="@Url.Action("Skills", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Skills </span>
                </a>

                <a href="@Url.Action("Awards", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Awards </span>
                </a>

                <a href="@Url.Action("Interests", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Interests </span>
                </a>


                <a href="@Url.Action("Projects", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Projects </span>
                </a>

                <a href="@Url.Action("CurriculumVitae", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Curriculum Vitae </span>
                </a>

                <a href="@Url.Action("Portfolio", "Portal")" class="list-group-item">
                    <span class=" glyphicon glyphicon-th" aria-hidden="true"></span><span> Portfolio </span>
                </a>
            </div>
        </div>
        <div class="col-md-10" id="body-wrapper"style="height: 820px;">
            @RenderBody()
        </div>
    </div>
</div>
<div class="container" style="padding: 0;">
    <div class="navbar navbar-inverse navbar-static-bottom margin-bottom-remove border-flatten">
        <p align="center" style="padding-top: 10px">
            Created by Paul O'Beirne <a href="http://www.bootply.com">GradFolio</a>
        </p>
    </div>
</div>


@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)


</body>
</html>

GradFolio Application/GradFolio/GradFolio.Web/Views/Shared/_Layout_Initial.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

<div class="container body-content">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>

GradFolio Application/GradFolio/GradFolio.Web/Views/Shared/_PdfLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MvcRazorToPdf</title>
    

    @RenderSection("css");

</head>
<body>
    @RenderBody()
</body>
</html>